name: Publish release to PyPI
description: Publish the target version to PyPI.

inputs:
  version:
    required: true
    type: string
  pypi-token:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download distribution artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ inputs.version }}
        path: dist-${{ inputs.version }}/

    - name: Upload distribution to PyPI
      # uses: pypa/gh-action-pypi-publish@release/v1
      # with:
      #   password: ${{ inputs.pypi-token }}
      run: |
        echo "Publishing to PyPI with version ${{ inputs.version }}"
        echo "Using token: ${{ inputs.pypi-token }}"
        # Add your PyPI publishing logic here
        # For example, you can use twine to upload the package
        # twine upload dist-${{ inputs.version }}/* -u __token__ -p ${{ secrets.pypi-token }} --skip-existing
