name: Publish release

on:
  push:
    branches:
      - master

jobs:
  publish_release:
    runs-on: ubuntu-latest

    environment:
      name: Publish
    
    steps:
      - name: Publish release
        if: github.base_ref == 'master' && (github.head_ref == 'patch-release' || github.head_ref == 'minor-release' || github.head_ref == 'major-release')
        run: |
          echo "Publishing release..."
          exit 0
